In [86]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests

source = requests.get('https://scomedy.com/quotes?page=1')

soup = bs(source.text, 'lxml')

In [88]:
#print(soup.prettify())

In [129]:
quote_list = []
comedian_list = []
view_list = []
theme_list = []

for i in range(1260):
  
    url = 'https://scomedy.com/quotes?page=' + str(i) #Affichage de toutes les pages du site scomedy
    source = requests.get(url) #Reqête de chaque url
    soup = bs(source.text, 'lxml')
    
    quotes = soup.find_all('div', {'class':'quote'})
    

    for quote in quotes:
        
        citation = quote.find('p').text
        quote_list.append(citation)
        
        comedian = quote.find('div',class_='comedian').text.split("\xa0")[1].split('\n')[0]
        comedian_list.append(comedian)
        
        view = int(quote.find('span',class_='views').text.split(" ")[1])
        view_list.append(view)
        
        tags_for_this_quote = []
        if quote.find('li'): 
        
            for element in quote.find_all('li'):
                theme = element.text.split("#")[1]
                tags_for_this_quote.append(theme)           
        else:
            tags_for_this_quote= None
            
        theme_list.append(tags_for_this_quote)
dict_quote ={'citation':quote_list,'auteur':comedian_list,'nbre_vues':view_list,'theme':theme_list}
quote_df = pd.DataFrame(dict_quote)
quote_df

,citation,auteur,nbre_vues,theme
0,"Well, birthdays are merely symbolic of how ano...",Jerry Seinfeld,1259,[birthday]
1,My perfect date night: I pick you up. In my Ki...,Aziz Ansari,968,"[danger, dating, restaurants]"
2,Jack and Jill went up the hill Both with a buc...,Andrew Dice Clay,938,None
3,"“Money doesn’t buy happiness.” Uh, do you live...",Daniel Tosh,791,[happiness]
4,"I mean, they don't grade fathers. But if your ...",Chris Rock,789,None
...,...,...,...,...
18883,Whenever I see an autobiography for sale in th...,Demetri Martin,4,None
18884,I saw a door that said exit only. So I entered...,Demetri Martin,4,None
18885,"I bought a dictionary. First thing I did was, ...",Demetri Martin,4,None
18886,When someone asks you the question 'Are you ti...,Demetri Martin,4,None
18887,I was seeing this girl and she wanted to get m...,Demetri Martin,4,None

In [122]:
quote_list = []
comedian_list = []
view_list = []
theme_list = []

for i in range(1260):
  
    url = 'https://scomedy.com/quotes?page=' + str(i) #Affichage de toutes les pages du site scomedy
    source = requests.get(url) #Reqête de chaque url
    soup = bs(source.text, 'lxml')
    
    quotes = soup.find_all('div', {'class':'quote'})
    
    #print(len(quotes))
    #print(" ")

    for quote in quotes:
        
        citation = quote.find('p').text
        quote_list.append(citation)
        #print(citation)
        #print(" ")
        comedian = quote.find('div',class_='comedian').text.split("\xa0")[1].split('\n')[0]
        comedian_list.append(comedian)
        #print(comedian)
        #print(" ")
        view = int(quote.find('span',class_='views').text.split(" ")[1])
        view_list.append(view)
        #print(" ")
        if quote.find('li'):
            tags_for_this_quote = []
            for element in quote.find_all('li'):
                theme = element.text.split("#")[1]
                #print(theme)    
        else:
            theme= None
        #print(" ")       
        theme_list.append(theme)
dict_quote ={'citation':quote_list,'auteur':comedian_list,'nbre_vues':view_list,'theme':theme_list}
quote_df = pd.DataFrame(dict_quote)
quote_df

,citation,auteur,nbre_vues,theme
0,"Well, birthdays are merely symbolic of how ano...",Jerry Seinfeld,1244,birthday
1,My perfect date night: I pick you up. In my Ki...,Aziz Ansari,959,restaurants
2,Jack and Jill went up the hill Both with a buc...,Andrew Dice Clay,933,None
3,"“Money doesn’t buy happiness.” Uh, do you live...",Daniel Tosh,785,happiness
4,"I mean, they don't grade fathers. But if your ...",Chris Rock,770,None
...,...,...,...,...
18883,Whenever I see an autobiography for sale in th...,Demetri Martin,4,None
18884,I saw a door that said exit only. So I entered...,Demetri Martin,4,None
18885,"I bought a dictionary. First thing I did was, ...",Demetri Martin,4,None
18886,When someone asks you the question 'Are you ti...,Demetri Martin,4,None
18887,I was seeing this girl and she wanted to get m...,Demetri Martin,4,None